POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###


POST http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

###

GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Sm9lQmlkZW4.GjSNsSse4owm-1fPgHhaObq8kb6ZfGuGT-AnnL7Jf50

###

GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.Sm9lQmlkZW4.GjSNsSse4owm-1fPgHhaObq8kb6ZfGuGT-AnnL7Jf50

###